{% set name = "transformations" %}
{% set version = "2024.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/transformations-{{ version }}.tar.gz
  sha256: cc924555c0e5ca0f7305bed277615599762d8f902367771b9c3f58b3dcf1be02

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
    - setuptools >=18.0
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - transformations
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://www.cgohlke.com/
  summary: Homogeneous Transformation Matrices and Quaternions
  dev_url: https://github.com/cgohlke/transformations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
