{% set name = "transformations" %}
{% set version = "2022.8.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/transformations-{{ version }}.tar.gz
  sha256: 40e69e262e611b43c69abbe172bdcdff3987b8aef5cafbec3a32c9fc75434955

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
    - setuptools >=18.0
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - transformations
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://www.cgohlke.com/
  summary: Homogeneous Transformation Matrices and Quaternions
  dev_url: https://github.com/cgohlke/transformations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
