{% set name = "transformations" %}
{% set version = "2026.1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/transformations-{{ version }}.tar.gz
  sha256: d7bdb5f7753b520facb42df6b21c6756126dd89a90700867a9162bebc6095c73

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pip
    - python
    - setuptools >=18.0
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - transformations
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://www.cgohlke.com/
  summary: Homogeneous Transformation Matrices and Quaternions
  dev_url: https://github.com/cgohlke/transformations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
